bib/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^synczotero/$', views.sync_zotero, name="synczotero"),
    url(r'^synczotero/result$', views.sync_zotero_action, name="synczotero_action")
]

thunau/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers
from places.apis_views import PlaceViewSet
from bib.api_views import BookViewSet

from vocabs import api_views

router = routers.DefaultRouter()
router.register(r'skoslabels', api_views.SkosLabelViewSet)
router.register(r'skosnamespaces', api_views.SkosNamespaceViewSet)
router.register(r'skosconceptschemes', api_views.SkosConceptSchemeViewSet)
router.register(r'skosconcepts', api_views.SkosConceptViewSet)
router.register(r'places', PlaceViewSet)
router.register(r'Book', BookViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webpage.urls', namespace='webpage')),
    url(r'^vocabs/', include('vocabs.urls', namespace='vocabs')),
    url(r'^vocabs-ac/', include('vocabs.dal_urls', namespace='vocabs-ac')),
    url(r'^datamodel/', include('django_spaghetti.urls', namespace='datamodel')),
    url(r'places/', include('places.urls', namespace='places')),
    url(r'^bib/', include('bib.urls', namespace='bib')),
    url(r'^documents/', include('documents.urls', namespace='documents')),
    url(r'^browsing/', include('browsing.urls', namespace='browsing')),
]

vocabs/urls.py
from django.conf.urls import url
from . import views
from . import import_views
from . import dal_views
from .models import SkosLabel, SkosConcept, SkosConceptScheme


urlpatterns = [
    url(r'^$', views.SkosConceptListView.as_view(), name='skosconcept_list'),
    url(r'^concepts/browse/$', views.SkosConceptFilterView.as_view(), name='browse_vocabs'),
    url(r'^import/$', import_views.import_skos, name='skos_import'),
    url(r'^import-from-csv/$', import_views.import_csv, name='skos_csv_import'),
    url(r'^(?P<pk>[0-9]+)$', views.SkosConceptDetailView.as_view(), name='skosconcept_detail'),
    url(r'^create/$', views.SkosConceptCreate.as_view(), name='skosconcept_create'),
    url(r'^update/(?P<pk>[0-9]+)$', views.SkosConceptUpdate.as_view(), name='skosconcept_update'),
    url(r'^delete/(?P<pk>[0-9]+)$', views.SkosConceptDelete.as_view(), name='skosconcept_delete'),
    url(r'^scheme/$', views.SkosConceptSchemeListView.as_view(), name='skosconceptscheme_list'),
    url(
        r'^scheme/(?P<pk>[0-9]+)$', views.SkosConceptSchemeDetailView.as_view(),
        name='skosconceptscheme_detail'),
    url(
        r'^scheme/create/$', views.SkosConceptSchemeCreate.as_view(),
        name='skosconceptscheme_create'),
    url(
        r'^scheme/update/(?P<pk>[0-9]+)$', views.SkosConceptSchemeUpdate.as_view(),
        name='skosconceptscheme_update'),
    url(r'^label/$', views.SkosLabelListView.as_view(), name='skoslabel_list'),
    url(
        r'^label/(?P<pk>[0-9]+)$', views.SkosLabelDetailView.as_view(),
        name='skoslabel_detail'),
    url(
        r'^label/create/$', views.SkosLabelCreate.as_view(),
        name='skoslabel_create'),
    url(
        r'^label/update/(?P<pk>[0-9]+)$', views.SkosLabelUpdate.as_view(),
        name='skoslabel_update'),
]

vocabs/models.py
import os
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.text import slugify


DEFAULT_PEFIX = os.path.basename(settings.BASE_DIR)

DEFAULT_NAMESPACE = "http://www.vocabs/{}/".format(DEFAULT_PEFIX)

LABEL_TYPES = (
    ('prefLabel', 'prefLabel'),
    ('altLabel', 'altLabel'),
    ('hiddenLabel', 'hiddenLabel'),
)

RELATION_TYPES = (
    ('narrower', 'narrower'),
    ('broader', 'broader'),
    ('related', 'related'),
    ('broadMatch', 'broadMatch'),
    ('relatedMatch', 'relatedMatch'),
    ('exactMatch', 'exactMatch'),
)


class SkosNamespace(models.Model):
    namespace = models.URLField(blank=True, default=DEFAULT_NAMESPACE)
    prefix = models.CharField(max_length=50, blank=True, default=DEFAULT_PEFIX)

    def __str__(self):
        return "{}".format(self.prefix)


class SkosConceptScheme(models.Model):
    dc_title = models.CharField(max_length=300, blank=True)
    namespace = models.ForeignKey(SkosNamespace, blank=True, null=True)
    dct_creator = models.URLField(blank=True)
    legacy_id = models.CharField(max_length=200, blank=True)

    def save(self, *args, **kwargs):
        if self.namespace is None:
            temp_namespace, _ = SkosNamespace.objects.get_or_create(
                namespace=DEFAULT_NAMESPACE, prefix=DEFAULT_PEFIX)
            temp_namespace.save()
            self.namespace = temp_namespace
        else:
            pass
        super(SkosConceptScheme, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('vocabs:skosconceptscheme_detail', kwargs={'pk': self.id})

    def __str__(self):
        return "{}:{}".format(self.namespace, self.dc_title)


class SkosLabel(models.Model):
    label = models.CharField(max_length=100, blank=True, help_text="The entities label or name.")
    label_type = models.CharField(
        max_length=30, blank=True, choices=LABEL_TYPES, help_text="The type of the label.")
    isoCode = models.CharField(
        max_length=3, blank=True, help_text="The ISO 639-3 code for the label's language.")

    def __str__(self):
        if self.label_type != "":
            return "{} @{} ({})".format(self.label, self.isoCode, self.label_type)
        else:
            return "{} @{}".format(self.label, self.isoCode)

    def get_absolute_url(self):
        return reverse('vocabs:skoslabel_detail', kwargs={'pk': self.id})


class SkosConcept(models.Model):
    pref_label = models.CharField(max_length=300, blank=True)
    pref_label_lang = models.CharField(max_length=3, blank=True, default="eng")
    scheme = models.ManyToManyField(SkosConceptScheme, blank=True)
    definition = models.TextField(blank=True)
    definition_lang = models.CharField(max_length=3, blank=True, default="eng")
    label = models.ManyToManyField(SkosLabel, blank=True)
    notation = models.CharField(max_length=300, blank=True)
    namespace = models.ForeignKey(SkosNamespace, blank=True, null=True)
    skos_broader = models.ManyToManyField('SkosConcept', blank=True, related_name="narrower")
    skos_narrower = models.ManyToManyField('SkosConcept', blank=True, related_name="broader")
    skos_related = models.ManyToManyField('SkosConcept', blank=True, related_name="related")
    skos_broadmatch = models.ManyToManyField('SkosConcept', blank=True, related_name="broadmatch")
    skos_exactmatch = models.ManyToManyField('SkosConcept', blank=True, related_name="exactmatch")
    skos_closematch = models.ManyToManyField('SkosConcept', blank=True, related_name="closematch")
    legacy_id = models.CharField(max_length=200, blank=True)

    @property
    def all_schemes(self):
        return ', '.join([x.dc_title for x in self.scheme.all()])

    def save(self, *args, **kwargs):
        if self.notation == "":
            temp_notation = slugify(self.pref_label, allow_unicode=True)
            concepts = len(SkosConcept.objects.filter(notation=temp_notation))
            if concepts < 1:
                self.notation = temp_notation
            else:
                self.notation = "{}-{}".format(temp_notation, concepts)
        else:
            pass

        if self.namespace is None:
            temp_namespace, _ = SkosNamespace.objects.get_or_create(
                namespace=DEFAULT_NAMESPACE, prefix=DEFAULT_PEFIX)
            temp_namespace.save()
            self.namespace = temp_namespace
        else:
            pass

        super(SkosConcept, self).save(*args, **kwargs)

    def __str__(self):
        return "{}".format(self.pref_label)

    def get_absolute_url(self):
        return reverse('vocabs:skosconcept_detail', kwargs={'pk': self.id})

vocabs/forms.py
from dal import autocomplete
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import SkosConcept, SkosConceptScheme, SkosLabel


class GenericFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(GenericFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.add_input(Submit('Filter', 'search'))


class UploadFileForm(forms.Form):
    file = forms.FileField()

    def __init__(self, *args, **kwargs):
        super(UploadFileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'import'),)


class SkosConceptForm(forms.ModelForm):
    class Meta:
        model = SkosConcept
        fields = "__all__"
        widgets = {
            'label': autocomplete.ModelSelect2Multiple(url='vocabs-ac:skoslabel-autocomplete'),
            'skos_broader': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skosconcept-autocomplete'),
            'skos_narrower': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skosconcept-autocomplete'),
            'skos_related': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skosconcept-autocomplete'),
            'skos_broadmatch': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skosconcept-autocomplete'),
            'skos_exactmatch': autocomplete.ModelSelect2Multiple(
                url='vocabs-ac:skosconcept-autocomplete'),
            'scheme': autocomplete.ModelSelect2Multiple(url='vocabs-ac:skosconceptscheme-autocomplete')
        }

    def __init__(self, *args, **kwargs):
        super(SkosConceptForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)


class SkosConceptSchemeForm(forms.ModelForm):
    class Meta:
        model = SkosConceptScheme
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(SkosConceptSchemeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)


class SkosLabelForm(forms.ModelForm):
    class Meta:
        model = SkosLabel
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(SkosLabelForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)

vocabs/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django_tables2 import SingleTableView, RequestConfig
from .models import SkosConcept, SkosConceptScheme, SkosLabel
from .forms import SkosConceptForm, SkosConceptSchemeForm, SkosLabelForm, GenericFilterFormHelper
from .tables import SkosConceptTable
from .filters import SkosConceptFilter


class GenericListView(SingleTableView):
    filter_class = None
    formhelper_class = None
    context_filter_name = 'filter'
    paginate_by = 25

    def get_queryset(self, **kwargs):
        qs = super(GenericListView, self).get_queryset()
        self.filter = self.filter_class(self.request.GET, queryset=qs)
        self.filter.form.helper = self.formhelper_class()
        return self.filter.qs

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()
        RequestConfig(self.request, paginate={
            'page': 1, 'per_page': self.paginate_by}).configure(table)
        return table

    def get_context_data(self, **kwargs):
        context = super(GenericListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        return context


class SkosConceptFilterView(GenericListView):
    model = SkosConcept
    table_class = SkosConceptTable
    template_name = 'vocabs/skosconcept_filter.html'
    filter_class = SkosConceptFilter
    formhelper_class = GenericFilterFormHelper


class SkosConceptDetailView(DetailView):

    model = SkosConcept
    template_name = 'vocabs/skosconcept_detail.html'


class SkosConceptListView(ListView):

    model = SkosConcept
    template_name = 'vocabs/skosconcept_list.html'


class SkosConceptCreate(CreateView):

    model = SkosConcept
    template_name = 'vocabs/skosconcept_create.html'
    form_class = SkosConceptForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptCreate, self).dispatch(*args, **kwargs)


class SkosConceptUpdate(UpdateView):

    model = SkosConcept
    form_class = SkosConceptForm
    template_name = 'vocabs/skosconcept_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptUpdate, self).dispatch(*args, **kwargs)


class SkosConceptDelete(DeleteView):
    model = SkosConcept
    template_name = 'vocabs/confirm_delete.html'
    success_url = reverse_lazy('vocabs:browse_vocabs')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptDelete, self).dispatch(*args, **kwargs)


#####################################################
#   ConceptScheme
#####################################################


class SkosConceptSchemeDetailView(DetailView):

    model = SkosConceptScheme
    template_name = 'vocabs/skosconceptscheme_detail.html'

    def get_context_data(self, **kwargs):
        context = super(SkosConceptSchemeDetailView, self).get_context_data(**kwargs)
        context["concepts"] = SkosConcept.objects.filter(scheme=self.kwargs.get('pk'))
        return context


class SkosConceptSchemeListView(ListView):

    model = SkosConceptScheme
    template_name = 'vocabs/skosconceptscheme_list.html'


class SkosConceptSchemeCreate(CreateView):

    model = SkosConceptScheme
    form_class = SkosConceptSchemeForm
    template_name = 'vocabs/skosconceptscheme_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptSchemeCreate, self).dispatch(*args, **kwargs)


class SkosConceptSchemeUpdate(UpdateView):

    model = SkosConceptScheme
    form_class = SkosConceptSchemeForm
    template_name = 'vocabs/skosconceptscheme_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosConceptSchemeUpdate, self).dispatch(*args, **kwargs)


###################################################
# SkosLabel
###################################################


class SkosLabelDetailView(DetailView):

    model = SkosLabel
    template_name = 'vocabs/skoslabel_detail.html'


class SkosLabelListView(ListView):

    model = SkosLabel
    template_name = 'vocabs/skoslabel_list.html'


class SkosLabelCreate(CreateView):

    model = SkosLabel
    template_name = 'vocabs/skoslabel_create.html'
    form_class = SkosLabelForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosLabelCreate, self).dispatch(*args, **kwargs)


class SkosLabelUpdate(UpdateView):

    model = SkosLabel
    form_class = SkosLabelForm
    template_name = 'vocabs/skoslabel_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SkosLabelUpdate, self).dispatch(*args, **kwargs)

vocabs/templates/vocabs/confirm_delete.html
{% extends "vocabs/plain_for_delete.html" %}
{% block content %}

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title">Confirm delete</h3>
      </div>
      <div class="modal-body">
       	<form action="" method="post">{% csrf_token %}
    		<h4>Are you sure you want to delete :<br /> <strong>{{ object }}</strong> ?</h4>
        <br>
        <a href="javascript:history.back()"><input class="btn btn-default" type="button" value="cancel"/></a>
    		<input  class="btn btn-danger" type="submit" value="yes, I want to delete" />
		</form>
      </div>
      <div class="modal-footer">
      </div>
    </div>

  </div>
</div>
</form>
{% endblock content %}
{% block scripts %}
<script type="text/javascript">
$(window).load(function(){
        $('#myModal').modal('show');
    });
</script>

{% endblock scripts %}

vocabs/templates/vocabs/skosconcept_detail.html
{% extends "webpage/base.html" %}
{% block Titel %} {{ object }} {% endblock %}
{% block content %}

<div class="container">
    <div class="panel panel-default procustom-panel-create">
        <div class="panel-heading procustom-panel-heading">
            <h1 style="text-align: center;">
               {% if object.pref_label %} {{object.pref_label }} {% endif %}<small>{{ object.namespace }}:{{ object.notation }}</small>
               <br>
               <small>a skos:Concept</small>
               {% if user.is_authenticated %}
                <a href="{% url 'vocabs:skosconcept_update' pk=object.id %}"> <span class="glyphicon glyphicon-pencil" aria-hidden="true" title="edit"></a>
                {% endif %}

            </h1>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-2">
                    <div class="panel panel-default">
                        <div class="panel-heading">skos:broader</div>
                        <div class="panel-body">
                            {% for x in object.skos_broader.all %}
                                <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a> <br/>
                            {% endfor %}
                            {% for x in object.broader.all %}
                                <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a> <br/>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">skos:related</div>
                        <div class="panel-body">
                            {% for x in object.skos_related.all %}
                                <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a> <br/>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">skos:broadMatch</div>
                        <div class="panel-body">
                            {% for x in object.skos_broadmatch.all %}
                                <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a> <br/>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">skos:closeMatch</div>
                        <div class="panel-body">
                            {% for x in object.skos_closematch.all %}
                                <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a> <br/>
                            {% endfor %}
                            {% for x in object.closematch.all %}
                                <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a> <br/>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">skos:exactMatch</div>
                        <div class="panel-body">
                            {% for x in object.skos_exactmatch.all %}
                                <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a> <br/>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="panel panel-default">

                        <div class="panel-body">
                            <table class="table table-bordered table-striped table-hover  ">
                                <tr>
                                    <td>skos:prefLabel| @{{ object.pref_label_lang }}</td>
                                    <td>{{ object.pref_label }} </td>
                                </tr>
                                <tr>
                                    <td>skos:definition | @{{ object.definition_lang }}</td>
                                    <td>{{ object.definition }}</td>
                                </tr>
                                <tr>
                                    <td>skos:inScheme</td>
                                    <td>
                                        {% for x in object.scheme.all %} {{ x }}
                                            {% if user.is_authenticated %}
                                                <a href="{% url 'vocabs:skosconceptscheme_update' pk=x.id %}"> <span class="glyphicon glyphicon-pencil" aria-hidden="true" title="edit"></a>
                                            {% endif %}<br/>
                                        {% endfor %} </td>
                                </tr>
                                <tr>
                                    <td>Labels</td>
                                    <td>
                                        {% for x in object.label.all %} {{ x }}
                                            {% if user.is_authenticated %}
                                                <a href="{% url 'vocabs:skoslabel_update' pk=x.id %}"> <span class="glyphicon glyphicon-pencil" aria-hidden="true" title="edit"></a>
                                            {% endif %}<br/>
                                        {% endfor %}
                                    </td>
                                </tr>
                                <tr>
                                    <td>legacy id</td>
                                    <td>{{ object.legacy_id }}</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="panel panel-default">
                        <div class="panel-heading">skos:narrower</div>
                        <div class="panel-body">
                            {% for x in object.skos_narrower.all %}
                                <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a> <br/>
                            {% endfor %}
                            {% for x in object.narrower.all %}
                                <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a> <br/>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a class ="btn btn-danger" href="{% url 'vocabs:skosconcept_delete' pk=object.id %}">delete</a>
</div>
{% endblock content %}

vocabs/templates/vocabs/skosconcept_filter.html
{% extends "vocabs/generic_list.html" %}
{% block list_title %}Browse SkosConcepts{% endblock %}

{% block create_button %}
{% if user.is_authenticated %}
 <div>
    <a class ="btn btn-primary btn-md"  href="{% url 'vocabs:skosconcept_create' %}">create new concept</a>
</div>
{% endif %}
{% endblock %}


{% block reset_button %}
 <a class ="btn btn-default"  href="{% url 'vocabs:browse_vocabs' %}">reset search</a>
{% endblock %}

vocabs/templates/vocabs/skosconcept_list.html
{% extends "webpage/base.html" %}

{% block content %}

<div class="container">
<div class="panel panel-default procustom-panel-list">
    <div class="panel-heading procustom-panel-heading">
        <h1>Concepts </h1>
        <div>
        <a class="btn btn-primary" href="{% url 'vocabs:skosconcept_create' %}" role="button">create concept</a>
      </div>
      <br>
    </div>
    <div class="panel-body procustom-panel-body">
       {% for object in object_list %}
       <li>
                 <a href="{% url 'vocabs:skosconcept_detail' pk=object.id %}">{{ object }}</a>
      </li>
       {% endfor %}

    </div>
</div>
</div>


{% endblock %}

vocabs/templates/vocabs/skosconceptscheme_detail.html
{% extends "webpage/base.html" %}

{% block content %}
<div class="container">
<div class="panel panel-default procustom-panel-list">
    <div class="panel-heading procustom-panel-heading">
      <h1>
          {{ object.namespace }}:{{ object.dc_title}}<br/> <small>a skos:ConceptScheme</small>
          {% if user.is_authenticated %}
              <a href="{% url 'vocabs:skosconceptscheme_update' pk=object.id %}"><span class="glyphicon glyphicon-pencil" aria-hidden="true" title="edit"></a>
          {% endif %}
      </h1>
      <small>dct:creator</small> {{ object.dct_creator }}
      <br>
    </div>
    <div class="panel-body procustom-panel-body">
      {% for x in concepts %}
      <li>
          <a href="{% url 'vocabs:skosconcept_detail' pk=x.id %}">{{ x }}</a>
      </li>
      {% endfor %}
      <!-- {% if user.is_authenticated %}
      <br>
      <a class="btn btn-primary" href="{% url 'vocabs:skosconceptscheme_update' pk=object.id %}" role="button">edit</a>
      {% endif %} -->

    </div>
</div>
</div>
{% endblock %}

vocabs/templates/vocabs/skosconceptscheme_list.html
{% extends "webpage/base.html" %}

{% block content %}
<div class="container">
<div class="panel panel-default procustom-panel-list">
    <div class="panel-heading procustom-panel-heading">
      <h1>Concept Schemes</h1>
      <div>
<a class="btn btn-primary" href="{% url 'vocabs:skosconceptscheme_create' %}" role="button">create concept scheme</a>
      </div>
      <br>
    </div>
<div class="panel-body procustom-panel-body">
{% for object in object_list %}
    <li>
        <a href="{% url 'vocabs:skosconceptscheme_detail' pk=object.id %}">{{ object }}</a>
    </li>
{% endfor %}
</div>
</div>
</div>
{% endblock %}

vocabs/templates/vocabs/skoslabel_detail.html
{% extends "webpage/base.html" %}

{% block content %}
<div class="container">
<div class="panel panel-default procustom-panel-list">
    <div class="panel-heading procustom-panel-heading">
      <h1>{{ object}}

      <br/> <small>skos:prefLabel</small>
      {% if user.is_authenticated %}
          <a href="{% url 'vocabs:skoslabel_update' pk=object.id %}"><span class="glyphicon glyphicon-pencil" aria-hidden="true" title="edit"></a>
      {% endif %}
      </h1>
    </div>
    <div class="panel-body procustom-panel-body">
      <table class="table table-bordered table-hover">
          <tr>
              <th>Label</th>
              <td>
              {{ object.label }}
              </td>
          </tr>
          <tr>
              <th>Label type</th>
              <td>
              {{ object.label_type }}
              </td>
          </tr>
          <tr>
              <th>IsoCode</th>
              <td>
              {{ object.isoCode }}
              </td>
          </tr>
      </table>

    </div>
</div>
</div>
{% endblock %}

vocabs/templates/vocabs/skoslabel_list.html
{% extends "webpage/base.html" %}

{% block content %}
<div class="container">
<div class="panel panel-default procustom-panel-list">
    <div class="panel-heading procustom-panel-heading">
      <h1>Labels</h1>
      <div>
      <a class="btn btn-primary" href="{% url 'vocabs:skoslabel_create' %}" role="button">create label</a>
    </div>
    <br>
  </div>
<div class="panel-body procustom-panel-body">

{% for object in object_list %}
    <li>
        <a href="{% url 'vocabs:skoslabel_detail' pk=object.id %}">{{ object }}</a>
    </li>
{% endfor %}
</div>
</div>
</div>

{% endblock %}