bib/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^synczotero/$', views.sync_zotero, name="synczotero"),
    url(r'^synczotero/result$', views.sync_zotero_action, name="synczotero_action")
]

browsing/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'documents/$', views.DocumentListView.as_view(), name='browse_documents'),
]

django_spaghetti/urls.py
from django.conf.urls import url
from django_spaghetti.views import plate

urlpatterns = [
    url(r'^$', plate, name='plate'),
]

thunau/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers
from places.apis_views import PlaceViewSet
from bib.api_views import BookViewSet

from vocabs import api_views

router = routers.DefaultRouter()
router.register(r'skoslabels', api_views.SkosLabelViewSet)
router.register(r'skosnamespaces', api_views.SkosNamespaceViewSet)
router.register(r'skosconceptschemes', api_views.SkosConceptSchemeViewSet)
router.register(r'skosconcepts', api_views.SkosConceptViewSet)
router.register(r'places', PlaceViewSet)
router.register(r'Book', BookViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webpage.urls', namespace='webpage')),
    url(r'^vocabs/', include('vocabs.urls', namespace='vocabs')),
    url(r'^vocabs-ac/', include('vocabs.dal_urls', namespace='vocabs-ac')),
    url(r'^datamodel/', include('django_spaghetti.urls', namespace='datamodel')),
    url(r'places/', include('places.urls', namespace='places')),
    url(r'^bib/', include('bib.urls', namespace='bib')),
    url(r'^documents/', include('documents.urls', namespace='documents')),
    url(r'^browsing/', include('browsing.urls', namespace='browsing')),
]

vocabs/urls.py
from django.conf.urls import url
from . import views
from . import import_views
from . import dal_views
from .models import SkosLabel, SkosConcept, SkosConceptScheme


urlpatterns = [
    url(r'^$', views.SkosConceptListView.as_view(), name='skosconcept_list'),
    url(r'^concepts/browse/$', views.SkosConceptFilterView.as_view(), name='browse_vocabs'),
    url(r'^import/$', import_views.import_skos, name='skos_import'),
    url(r'^import-from-csv/$', import_views.import_csv, name='skos_csv_import'),
    url(r'^(?P<pk>[0-9]+)$', views.SkosConceptDetailView.as_view(), name='skosconcept_detail'),
    url(r'^create/$', views.SkosConceptCreate.as_view(), name='skosconcept_create'),
    url(r'^update/(?P<pk>[0-9]+)$', views.SkosConceptUpdate.as_view(), name='skosconcept_update'),
    url(r'^delete/(?P<pk>[0-9]+)$', views.SkosConceptDelete.as_view(), name='skosconcept_delete'),
    url(r'^scheme/$', views.SkosConceptSchemeListView.as_view(), name='skosconceptscheme_list'),
    url(
        r'^scheme/(?P<pk>[0-9]+)$', views.SkosConceptSchemeDetailView.as_view(),
        name='skosconceptscheme_detail'),
    url(
        r'^scheme/create/$', views.SkosConceptSchemeCreate.as_view(),
        name='skosconceptscheme_create'),
    url(
        r'^scheme/update/(?P<pk>[0-9]+)$', views.SkosConceptSchemeUpdate.as_view(),
        name='skosconceptscheme_update'),
    url(r'^label/$', views.SkosLabelListView.as_view(), name='skoslabel_list'),
    url(
        r'^label/(?P<pk>[0-9]+)$', views.SkosLabelDetailView.as_view(),
        name='skoslabel_detail'),
    url(
        r'^label/create/$', views.SkosLabelCreate.as_view(),
        name='skoslabel_create'),
    url(
        r'^label/update/(?P<pk>[0-9]+)$', views.SkosLabelUpdate.as_view(),
        name='skoslabel_update'),
]

webpage/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from . import views

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    url(r'^$', views.StartView.as_view(), name="start"),
    url(r'^favicon\.ico$', favicon_view),
    url(r'^imprint/$', views.ImprintView.as_view(), name='imprint'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^accounts/login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
]

webpage/forms.py
# -*- coding: utf-8 -*-
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class form_user_login(forms.Form):
    username = forms.CharField(label='Username', widget=forms.TextInput)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(form_user_login, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Login'))

webpage/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView
from django.contrib.auth import authenticate, login, logout
from .forms import form_user_login


class AboutView(TemplateView):
    template_name = "webpage/about.html"


class StartView(TemplateView):
    template_name = "webpage/index.html"


class ImprintView(TemplateView):
    template_name = "webpage/imprint.html"


#################################################################
#               views for login/logout                          #
#################################################################

def user_login(request):
    if request.method == 'POST':
        form = form_user_login(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user and user.is_active:
                login(request, user)
                return HttpResponseRedirect(request.GET.get('next', '/'))
            return HttpResponse('user does not exist')
    else:
        form = form_user_login()
        return render(request, 'webpage/user_login.html', {'form': form})


def user_logout(request):
    logout(request)
    return render_to_response('webpage/user_logout.html')

webpage/templates/webpage/about.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% load webpage_extras %}
{% block title %} About {% endblock %}
{% block content %}
<div class="container">
    <h1>{% projects_metadata 'title' %}</h1>
    <p>
        {% projects_metadata 'description' %}
    </p>
</div>
{% endblock %}

webpage/templates/webpage/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load webpage_extras %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %} {% projects_metadata 'title' %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block metaDescription %}
        <meta name="description" content="{{ metadata.description }}">
        <meta name="author" content="{{ metadata.author }}">
    {% endblock %}
    <!-- favicons -->
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'webpage/img/favicon/apple-touch-icon.png' %}"/>
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'webpage/img/favicon/favicon-32x32.png' %}"/>
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'webpage/img/favicon/favicon-16x16.png' %}"/>
        <link rel="manifest" href="{% static 'webpage/img/favicon/manifest.json' %}"/>
        <link rel="mask-icon" href="{% static 'webpage/img/favicon/safari-pinned-tab.svg' %}" color="#00aba9"/>
        <meta name="theme-color" content="#ffffff"/>
    <!--favicons end -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'webpage/libraries/bootstrap337/css/bootstrap.min.css' %}" />
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'webpage/css/style.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Libre+Franklin:400,500" rel="stylesheet">
    <!-- custom less -->
    <link rel="stylesheet/less" type="text/css" href="{% static 'webpage/css/style.less' %}" />
    <!--scroll to top CSS -->
    <link rel="stylesheet" href="{% static 'webpage/libraries/scroll-to-top/css/ap-scroll-top.min.css'%}" />
    <!-- LESS -->
    <script type="text/javascript" src="{% static 'webpage/libraries/less/less.min.js' %}"></script>
    <!-- jQuery -->
    <script type="text/javascript" src="{% static 'webpage/libraries/jquery/jquery.js' %}"></script>
    <!--scroll to top -->
    <script src="{% static 'webpage/libraries/scroll-to-top/js/ap-scroll-top.min.js'%}"></script>
    <!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
    <script type="text/javascript">
        window.cookieconsent_options = {
            "message":"This website uses cookies to ensure you get the best experience on our website",
            "dismiss":"Got it!",
            "learnMore":"More info",
            "link":"{% url 'webpage:imprint' %}",
            "theme":"dark-bottom"};
    </script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
    <!-- End Cookie Consent plugin -->
    <!-- cool-share plugin http://tutorialzine.com/2014/08/cool-share-jquery-plugin/ -->
    <link rel="stylesheet" href="{% static 'webpage/libraries/cool-share/plugin.css' %}" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" />
    <script src="{% static 'webpage/libraries/cool-share/plugin.js' %}"></script>
    <!-- End fo cool-share -->
    <!-- Piwik -->
    <script type="text/javascript">
        var _paq = _paq || [];
        /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);
        (function() {
            var u="//piwik.apollo.arz.oeaw.ac.at/";
            _paq.push(['setTrackerUrl', u+'piwik.php']);
            _paq.push(['setSiteId', '63']);
            var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
            g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
        })();
    </script>
    <!-- End Piwik Code -->
    {% block scriptHeader %}
    {% endblock %}
</head>
<body>
<header class="page-header procustom-header">
    <div class="container" id="procustom-affix">
        <div class="logo-container">
            <a href="{% url 'webpage:start' %}" class="navlink">
                <h2>place for some logo</h2>
            </a>
        </div>
    </div>
    <nav class="navbar navbar-default navbar-static-top procustom-navbar" id="top-procustom-navbar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation!</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                 <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Home
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu procustom-dropdown-menu">
                            <li><a href="{% url 'webpage:start' %}">{% projects_metadata 'title' %}</a></li>
                            <li><a href="{% url 'webpage:about' %}">About</a></li>
                            <li><a href="{% url 'datamodel:plate' %}">Application's data model</a></li>
                            <li><a href="{% url 'webpage:imprint' %}">Impressum / Imprint</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        {% if user.is_authenticated %}
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            Curate and Browse the Data <span class="caret"></span>
                        </a>
                        {% else %}
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            Browse the Data <span class="caret"></span>
                        </a>
                        {% endif %}
                        <ul class="dropdown-menu procustom-dropdown-menu">
                            {% if user.is_authenticated %}
                                <li><a href="{% url 'browsing:browse_documents' %}">Documents</a></li>
                                <li><a href="{% url 'places:place_list' %}">Locations</a></li>
                                <li role="separator" class="divider"></li>
                                <li role="separator" class="divider"></li>
                                <!-- <li><a href="{% url 'bib:synczotero' %}">Import new Items from Zotero</a></li> -->
                            {% endif %}
                        </ul>
                    </li>
                    <!-- <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            Analyze the Data <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu procustom-dropdown-menu"></ul>
                    </li> -->
                    {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            Vocabs Curationb <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu procustom-dropdown-menu">
                            <li><a href="{% url 'vocabs:skosconceptscheme_list' %}">Concept Schemes</a></li>
                            <li><a href="{% url 'vocabs:browse_vocabs' %}">Concepts</a></li>
                            <li><a href="{% url 'vocabs:skoslabel_list' %}">Labels</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'vocabs:skos_import' %}">Import SKOS (RDF/XML)</a></li>
                            <li><a href="{% url 'vocabs:skos_csv_import' %}">Import Vocabs from CSV</a></li>
                            <li><a href="{% url 'api-root' %}">Export SKOS (API)</a></li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        {% if user.is_authenticated %}
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                                {{ user.get_username }}
                            </a>
                            <ul class="dropdown-menu procustom-dropdown-menu">
                                <li><a href="{% url 'webpage:user_logout' %}">Log-Out</a></li>
                            </ul>
                        {% else %}
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                            </a>
                            <ul class="dropdown-menu procustom-dropdown-menu">
                                <li><a href="{% url 'webpage:user_login' %}">Log-In</a></li>
                            </ul>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<section class="main-content">
    {% block procustom-index %}{% endblock %}
    <div id="content" class="container">{% block content %}{% endblock %}</div>
</section>
<div style="text-align:center">
    <span class="socialShare"><!-- The share buttons will be inserted here --></span>
</div>
<footer>
    <div class="container">
        <div class="row text-center">
            <div class="col-sm-6">
                <a href="https://www.oeaw.ac.at/acdh/" class="navlink" target="_blank">
                    <img src="{% static 'webpage/img/acdh_logo_02.png' %}" id="acdh-logo" alt="ACDH" title="Austrian Centre for Digital Humanities"/>
                </a>
            </div>
            <div class="col-sm-6">
                <a href="{% projects_metadata 'github' %}" class="navlink" target="_blank">
                    <img src="{% static 'webpage/img/GitHub-Mark-Light-64px.png' %}" id="github-logo" alt="{{ metadata.github }}" title="Github source code"/>
                </a>
            </div>
        </div>
        <div align="right">
            <small>Version: {% projects_metadata 'version' %}</small>
        </div>
    </div>
</footer>
{% block scripts %}
<script type="text/javascript" src="{% static 'webpage/libraries/bootstrap335/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'webpage/libraries/bootstrap335/js/bootstrap-tab.js' %}"></script>
<!-- cool share -->
<script type="text/javascript">
    $(function (){
        var options = {
            twitter: {
            text: '',
            via: ''
        },
        facebook : true,
        googlePlus : true
        };
        $('.socialShare').shareButtons(options);
    });
</script>
<!-- scroll-up-bottom -->
<script type="text/javascript">
    $(document).ready(function() {
        $.apScrollTop({'onInit': function(evt) {console.log('apScrollTop: init');}});
    });
</script>
{% endblock %}
{% block scripts2 %}
{% endblock scripts2 %}
<noscript>
    <img src="//piwik.apollo.arz.oeaw.ac.at/piwik.php?idsite=48" style="border:0;" alt=""/>
</noscript>
</body>
</html>

webpage/templates/webpage/confirm_delete.html
{% extends "webpage/base.html" %}
{% block content %}
<!-- Launch modal on page load http://stackoverflow.com/questions/10233550/launch-bootstrap-modal-on-page-load -->
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title">Confirm delete</h3>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <h4>
                        Are you sure you want to delete the {{ object.get_classname }}:<br />
                        <strong>{{ object }}</strong> ?
                    </h4>
                    <input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer"></div>
        </div>
    </div>
</div>
</form>
{% endblock content %}
{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        $(window).load(function(){
            $('#myModal').modal('show');
        });
    </script>
{% endblock scripts %}

webpage/templates/webpage/imprint.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% load webpage_extras %}
{% block title %} Imprint {% endblock %}
{% block content %}
<div class="container">
<div class="imprint">
    <h1>Impressum | imprint</h1>
    <div lang="de">
        <h1>Offenlegung gemäß §§ 24, 25 Mediengesetz und § 5 E-Commerce-Gesetz</h1>
        <h2>Medieninhaberin, Herausgeberin, inhaltliche und redaktionelle Verantwortung, Dienstanbieterin:</h2>
        <p>
            <a href="http://www.oeaw.ac.at">Österreichische Akademie der Wissenschaften</a><br/>
            Juristische Person öffentlichen Rechts (BGBl 569/1921 idF BGBl I 130/2003)<br/>
            <a href="https://acdh.oeaw.ac.at">Austrian Centre for Digital Humanities (ACDH)</a><br/>
            Dr. Ignaz Seipel-Platz 2, 1010 Wien, Österreich<br/>
            E-Mail: <a href="mailto:acdh-tech@oeaw.ac.att" style="color:black">acdh-tech@oeaw.ac.at</a>
        </p>
        <h2>Unternehmensgegenstand:</h2>
        <p>
            Die Österreichische Akademie der Wissenschaften (ÖAW) hat den gesetzlichen Auftrag, die
            Wissenschaft in jeder Hinsicht zu fördern. Als Gelehrtengesellschaft pflegt die ÖAW den
            Diskurs und die Zusammenarbeit der Wissenschaft mit Öffentlichkeit, Politik und
            Wirtschaft. <br/>
            Das Austrian Centre for Digital Humanities (ACDH) ist ein Institut der ÖAW, das mit dem
            Ziel gegründet wurde, digitale Methoden und Ansätze in den geisteswissenschaftlichen
            Disziplinen zu fördern. Das ACDH unterstützt digitale Forschung in vielfältiger Weise.
            <br/>
            {% projects_metadata 'purpose_de' %}

        </p>
        <h2>Vertretungsbefugte Organe:</h2>
        <p>
            Präsident: Univ.-Prof. Dr. Anton Zeilinger<br/>
            Vizepräsident: Univ.-Doz. Dr. phil. Michael Alram<br/>
            Klassenpräsidentin: Univ.-Prof. Dr. Brigitte Mazohl, <br/>
            Klassenpräsident: Univ.-Prof. Dipl.-Ing. Dr.techn. Georg Brasseur<br/>
            Als Aufsichtsorgan besteht der Akademierat. Siehe mehr dazu unter
            <a href="http://www.oeaw.ac.at/die-oeaw/gremien-der-oeaw/akademierat/">
                http://www.oeaw.ac.at/die-oeaw/gremien-der-oeaw/akademierat/
            </a>
        </p>
        <h2>Grundlegende Richtung:</h2>
        <p>
            {% projects_metadata 'purpose_de' %}
        </p>
        <h2>Haftungsausschluss:</h2>
        <p>
            Die Österreichische Akademie der Wissenschaften übernimmt keinerlei Gewähr für die
            Aktualität, Korrektheit, Vollständigkeit oder Qualität der bereitgestellten
            Informationen.<br/>
            Im Falle des Bestehens von Links auf Webseiten anderer Medieninhaber, für deren Inhalt
            die ÖAW weder direkt oder indirekt mitverantwortlich ist, übernimmt die ÖAW keine
            Haftung für deren Inhalte und schließt jegliche Haftung hierfür aus.
        </p>
        <!-- <h2>Urheberrechtlicher Hinweis:</h2>
            <p>
                Diese Seite und ihre Inhalte sind, sofern nicht anders gekennzeichnet, unter der
                creative commons Lizenz
                <a href="http://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA 4.0</a>
                International lizensiert (Namensnennung – Weitergabe unter gleichen Bedingungen).
            </p> -->
        <h2>Datenschutzrechtlicher Hinweis:</h2>
        <p>
            Wir weisen darauf hin, dass zum Zwecke der Systemsicherheit und der Übersicht über das
            Nutzungsverhalten der Besuchenden im Rahmen von Cookies diverse personenbezogene Daten
            (Besuchszeitraum, Betriebssystem, Browserversion, innere Auflösung des Browserfensters,
            Herkunft nach Land, wievielter Besuch seit Beginn der Aufzeichnung) mittels
            <a href="http://piwik.org/">Piwik-Tracking</a> gespeichert werden. Die Daten werden bis
            auf weiteres gespeichert. Soweit dies erfolgt, werden diese Daten nicht ohne Ihre
            ausdrückliche Zustimmung an Dritte weitergegeben.<br/>
            Durch die Nutzung der Website erklären Sie sich mit der Art und Weise sowie dem Zweck
            der Datenverarbeitung einverstanden. Durch eine entsprechende Einstellung in Ihrem
            Browser können Sie die Speicherung der Cookies verhindern. In diesem
            Fall stehen Ihnen aber gegebenenfalls nicht alle Funktionen der Website zur
            Verfügung.<br/>
            Die im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten dürfen von
            Dritten nicht zur Übersendung von nicht ausdrücklich angeforderter Werbung und
            Informationsmaterialien verwendet werden. Einer derartigen Verwendung wird
            hiermit ausdrücklich widersprochen.
        </p>
    </div>
    <hr/>
    <div lang="en">
        <h1>Legal disclosure according to §§ 24, 25 Austrian media law and § 5 E-Commerce law</h1>
        <h2>Media owner, publisher, responsible for content and editorial office, service provider:</h2>
        <p>
            <a href="http://www.oeaw.ac.at">Austrian Academy of Sciences</a>
            <br/>
            Corporate body organized under public law (BGBl 569/1921 idF BGBl I 130/2003)<br/>
            <a href="https://acdh.oeaw.ac.at">Austrian Centre for Digital Humanities (ACDH)</a>
            <br/>
            Dr. Ignaz Seipel-Platz 2, 1010 Vienna, Austria<br/>
            E-Mail: <a href="mailto:acdh-tech@oeaw.ac.att" style="color:black">acdh-tech@oeaw.ac.at</a>
        </p>
        <h2>Nature and purpose of the business:</h2>
        <p>
            The Austrian Academy of Sciences (OEAW) has the legal duty to support the
            sciences and humanities in every respect. As a learned society, the OEAW fosters
            discourse and cooperation between science and society, politics and economy.<br/>
            The Austrian Centre for Digital Humanities (ACDH) is an OEAW institute founded with
            the goal to support digital methods in arts and humanities disciplines.
            The ACDH supports digital research in manifold ways.<br/>
            {% projects_metadata 'purpose_en' %}
        </p>
        <h2>Signing power:</h2>
        <p>
            President: Univ.-Prof. Dr. Anton Zeilinger<br/>
            Vice president: Univ.-Doz. Dr. phil. Michael Alram<br/>
            Class presidents: Univ.-Prof. Dr. Brigitte Mazohl, Univ.-Prof. Dipl.-Ing. Dr.techn. Georg Brasseur<br/>
            Supervisory body:  Academy council. For more information, please visit
            <a href="http://www.oeaw.ac.at/die-oeaw/gremien-der-oeaw/akademierat/">
                http://www.oeaw.ac.at/die-oeaw/gremien-der-oeaw/akademierat/
            </a>
        </p>
        <h2>Main aim:</h2>
        <p>
            {% projects_metadata 'purpose_en' %}
        </p>
        <h2>Disclaimer:</h2>
        <p>
            The Austrian Academy of Sciences does not take responsibility for the nature, accuracy,
            entirety or quality of the provided information.<br/>
            In the case of links to websites of other media owners, whose content the OEAW is
            neither directly nor indirectly responsible for, the OEAW does not assume liability for
            their content and excludes any liability in this case.
        </p>
        <!-- <h2>Copyright notice:</h2>
        <p>
            This website and its content is, unless indicated otherwise, licensed under a creative
            commons <a href="http://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA 4.0</a>
            International license (Attribution – Share alike).
        </p> -->
        <h2>Data privacy notice:</h2>
        <p>
            This is a notice to indicate that for reasons of system security and overview of user
            behavior, personal data of users of this website (visiting period, operating system,
            browser version, browser resolution, country of origin, number of visits) will be stored
            using cookies and <a href="http://piwik.org/">piwik tracking</a>. Data will be stored
            until further notice. Data will not be disseminated without your explicit consent.<br/>
            By using this website, you agree to the manner and purposes of data processing. You can
            disable cookies in your browser settings. However, this might limit functionality of
            this website.<br/>
            The contact data published in the context of the imprint duty may not be used to send
            promotional or informational material not explicitly requested. We explicitly disagree
            with this usage.
        </p>
    </div>
</div>
</div>
{% endblock %}

webpage/templates/webpage/user_login.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <br />
    {% if form.errors %}
        <p style="color:red;">Please correct the error{{ form.errors|pluralize }} below.</p>
    {% endif %}
    {% load crispy_forms_tags %}
    {% crispy form form.helper %}
</div>
{% endblock %}