bib/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^synczotero/$', views.sync_zotero, name="synczotero"),
    url(r'^synczotero/result$', views.sync_zotero_action, name="synczotero_action")
]

documents/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^(?P<pk>[0-9]+)$', views.DocumentDetailView.as_view(), name='document_detail'),
    url(r'^create/$', views.DocumentCreate.as_view(), name='document_create'),
    url(r'^update/(?P<pk>[0-9]+)$', views.DocumentUpdate.as_view(), name='document_update'),
    url(r'^delete/(?P<pk>[0-9]+)$', views.DocumentDelete.as_view(), name='document_delete'),
]

thunau/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers
from places.apis_views import PlaceViewSet
from bib.api_views import BookViewSet

from vocabs import api_views

router = routers.DefaultRouter()
router.register(r'skoslabels', api_views.SkosLabelViewSet)
router.register(r'skosnamespaces', api_views.SkosNamespaceViewSet)
router.register(r'skosconceptschemes', api_views.SkosConceptSchemeViewSet)
router.register(r'skosconcepts', api_views.SkosConceptViewSet)
router.register(r'places', PlaceViewSet)
router.register(r'Book', BookViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('webpage.urls', namespace='webpage')),
    url(r'^vocabs/', include('vocabs.urls', namespace='vocabs')),
    url(r'^vocabs-ac/', include('vocabs.dal_urls', namespace='vocabs-ac')),
    url(r'^datamodel/', include('django_spaghetti.urls', namespace='datamodel')),
    url(r'places/', include('places.urls', namespace='places')),
    url(r'^bib/', include('bib.urls', namespace='bib')),
    url(r'^documents/', include('documents.urls', namespace='documents')),
    url(r'^browsing/', include('browsing.urls', namespace='browsing')),
]

documents/models.py
from django.db import models
from django.core.urlresolvers import reverse
from vocabs.models import SkosConcept
from places.models import Place
from bib.models import Book


class Institution(models.Model):
    name = models.CharField(max_length=300, blank=True)
    abbreviation = models.CharField(max_length=300, blank=True)
    identifier = models.CharField(max_length=300, blank=True)
    parent_institution = models.ForeignKey('Institution', blank=True, null=True)

    def __str__(self):
        return "{}".format(self.name)


class Person(models.Model):
    forename = models.CharField(max_length=300, blank=True)
    name = models.CharField(max_length=300, blank=True)
    institution = models.ForeignKey(Institution, blank=True, null=True)
    identifier = models.CharField(max_length=300, blank=True)

    def __str__(self):
        return "{}".format(self.name)


class Document(models.Model):
    legacy_id = models.CharField(max_length=300, blank=True, verbose_name='ID')
    filename = models.CharField(max_length=300, blank=True, verbose_name="Dateiname")
    entry_order = models.CharField(
        max_length=300, blank=True, verbose_name="Ordnungskriterium/Eingabe"
    )
    medium = models.ForeignKey(
        SkosConcept, blank=True, null=True, related_name='medium', verbose_name="Medium"
    )
    analogue_format = models.ForeignKey(
        SkosConcept, blank=True, null=True, related_name="analogue_format",
        verbose_name="Analoges Format"
    )
    author = models.ManyToManyField(
        Person, blank=True, related_name="author", verbose_name="Autor"
    )
    institution = models.ManyToManyField(
        Institution, blank=True, verbose_name="Institution", related_name="institution_document"
    )
    date_analogue = models.CharField(max_length=300, blank=True, verbose_name="Analoges Datum")
    date_digitization = models.DateField(
        auto_now=False, blank=True, null=True, verbose_name="Datum der Digitalisierung"
    )
    digital_format = models.ForeignKey(
        SkosConcept, blank=True, null=True, related_name="digital_format",
        verbose_name="Speicherformat"
    )
    note = models.TextField(blank=True, verbose_name="Anmerkung")
    content = models.TextField(blank=True, verbose_name="Inhalt")
    topic_group = models.ForeignKey(
        SkosConcept, blank=True, null=True, related_name="topic_group",
        verbose_name="Gruppe"
    )
    combination = models.CharField(max_length=300, blank=True, verbose_name="Kombination")
    location_id = models.CharField(max_length=300, blank=True, verbose_name="Fundnummer in FDB")
    place = models.ForeignKey(Place, blank=True, null=True, verbose_name="KG/Areal")
    location_digitized_object = models.CharField(
        max_length=300, blank=True, verbose_name="Aufbewahrung Datei"
    )
    location_analogue = models.CharField(max_length=300, blank=True, verbose_name="Standort analog")
    curator = models.ForeignKey(
        Person, blank=True, null=True, verbose_name="Bearbeiter Digitalisierung"
    )
    filesize = models.FloatField(blank=True, null=True, verbose_name="Dateigröße KB")
    place_digizization = models.ForeignKey(
        Institution, blank=True, null=True, related_name="place_digizization",
        verbose_name="Ort der Digitalisierung"
    )
    reference = models.ManyToManyField(Book, blank=True, verbose_name="Literaturzitate")
    path = models.CharField(max_length=300, blank=True, verbose_name="Dateipfad")
    amendments = models.TextField(blank=True, verbose_name="Ergänzungen")

    def __str__(self):
        return "{}".format(self.filename)

    def get_absolute_url(self):
        return reverse('documents:document_detail', kwargs={'pk': self.id})

documents/forms.py
from dal import autocomplete
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import Document


class GenericFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(GenericFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.add_input(Submit('Filter', 'search'))


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(DocumentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'
        self.helper.add_input(Submit('submit', 'save'),)

documents/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from .models import Document
from .forms import DocumentForm


class DocumentDetailView(DetailView):

    model = Document
    template_name = 'documents/document_detail.html'


class DocumentListView(ListView):

    model = Document
    template_name = 'documents/document_list.html'


class DocumentCreate(CreateView):

    model = Document
    template_name = 'documents/document_create.html'
    form_class = DocumentForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DocumentCreate, self).dispatch(*args, **kwargs)


class DocumentUpdate(UpdateView):

    model = Document
    form_class = DocumentForm
    template_name = 'documents/document_create.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DocumentUpdate, self).dispatch(*args, **kwargs)


class DocumentDelete(DeleteView):
    model = Document
    template_name = 'vocabs/confirm_delete.html'
    success_url = reverse_lazy('browsing:browse_documents')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DocumentDelete, self).dispatch(*args, **kwargs)

documents/templates/documents/document_create.html
{% extends "webpage/base.html" %}
{% block Titel %} Create/Modify a Document {% endblock %}
{% block content %}
{% load crispy_forms_tags %}

<div class="container">
<div class="panel panel-default procustom-panel-create">
    <div class="panel-heading procustom-panel-heading">
        <h1>Create/Edit Document</h1>
        {% if object %}
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">{{ object }}</li>
            </ol>
      {% endif %}

    </div>
    <div class="panel-body">
        {% crispy form %}
    </div>
</div>
</div>

{% endblock content %}

documents/templates/documents/document_detail.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block scriptHeader %}
<!--leafletjs -->
    <link rel="stylesheet" href="{% static 'webpage/libraries/leaflet/leaflet.css' %}" />
    <script src="{% static 'webpage/libraries/leaflet/leaflet.js' %}"></script>
        <style>
            #map { height: 500px; }
        </style>

{% endblock %}
{% block content %}
    <h1>{{ object }}</h1>

    <legend>Original Document</legend>
    <table class="table table-bordered table-hover">
        <tr>
            <th class="col-sm-3">legacy ID</th>
            <td>{{object.legacy_id}}</td>
        </tr>
        <tr>
            <th>Dateiname</th>
            <td>{{ object.filename }}</td>
        </tr>
        <tr>
            <th>Ordnungskriterium/Eingabe</th>
            <td>{{ object.entry_order }}</td>
        </tr>
        <tr>
            <th>Medium</th>
            <td>{{ object.medium }}</td>
        </tr>
        <tr>
            <th>Analoges Format</th>
            <td>{{ object.analogue_format }}</td>
        </tr>
        <tr>
            <th>Autor</th>
            <td>
                {% for x in object.author.all %}
                    {{ x.name }}, {{ x.forename }} </br>
                {% endfor %}
            </td>
        </tr>
        <tr>
            <th>Institution</th>
            <td>
                {% for x in object.institution.all %}
                    {{ x.name }} </br>
                {% endfor %}
            </td>
        </tr>
        <tr>
            <th>Analoges Datum</th>
            <td>{{ object.date_analogue }}</td>
        </tr>
        <tr>
            <th>Anmerkung</th>
            <td>{{ object.note }}</td>
        </tr>
        <tr>
            <th>Inhalt</th>
            <td>{{ object.content }}</td>
        </tr>
        <tr>
            <th>Gruppe</th>
            <td>{{ object.topic_group }}</td>
        </tr>
        <tr>
            <th>Kombination</th>
            <td>{{ object.combination }}</td>
        </tr>
        <tr>
            <th>Fundnummer in FDB</th>
            <td>{{ object.location_id }}</td>
        </tr>

        <tr>
            <th>Standort analog</th>
            <td>{{ object.location_analogue }}</td>
        </tr>
        <tr>
            <th>Ergänzungen</th>
            <td>{{ object.amendments }}</td>
        </tr>
    </table>

    <legend>Process of Digitization</legend>
    <table class="table table-bordered table-hover">
        <tr>
            <th class="col-sm-3">Bearbeiter Digitalisierung</th>
            <td>{{ object.curator.name }}, {{ object.curator.forename }}</td>
        </tr>
        <tr>
            <th>Ort der Digitalisierung</th>
            <td>{{ object.place_digizization }}</td>
        </tr>
        <tr>
            <th>Datum der Digitalisierung</th>
            <td>{{ object.date_digitization }}</td>
        </tr>
    </table>

    <legend>Digitzied Object</legend>
    <table class="table table-bordered table-hover">
        <tr>
            <th class="col-sm-3">Dateipfad</th>
            <td>{{ object.path }}</td>
        </tr>
        <tr>
            <th>Dateigröße KB</th>
            <td>{{ object.filesize }}</td>
        </tr>

        <tr>
            <th>Aufbewahrung Datei</th>
            <td>{{ object.location_digitized_object }}</td>
        </tr>
        <tr>
            <th>Speicherformat</th>
            <td>{{ object.digital_format }}</td>
        </tr>
    </table>


    <legend>KG/Areal: {{object.place}}</legend>
        {% if object.place.lat %}
            <div id="map"></div><br/>
        {% endif %}

        {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'documents:document_update' pk=object.pk %}" role="button">edit document</a>
            <a class ="btn btn-danger" href="{% url 'documents:document_delete' pk=object.id %}">delete</a>

        {% endif %}
{% endblock %}
{% block scripts2 %}
    <script type="text/javascript">

        var gps1 = {{ object.place.lat }};
        var gps2 = {{ object.place.lng }};
        var map = L.map('map').setView([gps1, gps2], 6);

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
            attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
            maxZoom: 18,
            id: 'mapbox.light',
            accessToken: 'pk.eyJ1Ijoic2VubmllcmVyIiwiYSI6ImNpbHk1YWV0bDAwZnB2dW01d2l1Y3phdmkifQ.OljQLEhqeAygai2y6VoSwQ'
            }).addTo(map);

        L.marker([gps1 , gps2]).addTo(map)
        .bindPopup('<a href="#">{{ object.place.name }}</a>')
        .openPopup();

    </script>
{% endblock scripts2 %}